import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
import User from './models/User.js';
import Product from './models/Product.js';

dotenv.config();

const products = [
  // ============ APPLE (I PHONE) ============
  { name: 'Apple iPhone 15 256GB Blue', brand: 'Apple', category: 'Mobiles', price: 74900, mrp: 89900, stock: 1, description: 'Dynamic Island, 48MP camera system, USB-C, Ceramic Shield front, Colorful new design.', specifications: { RAM: '6 GB', Storage: '256 GB', 'Screen Size': '6.1 inch', Color: 'Blue', Battery: '3349 mAh', Processor: 'A16 Bionic', Camera: '48 MP', OS: 'iOS 17', Weight: '171 g', '5G': 'Yes', Warranty: '1 Year Apple India' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg'], ratings: 4.6, reviewCount: 189, isFeatured: true, emiAvailable: true, emiStarting: 6242, exchangeAvailable: true, tags: ['5g', 'apple', 'flagship', 'ios'] },
  { name: 'Apple iPhone 16 128GB Teal', brand: 'Apple', category: 'Mobiles', price: 79900, mrp: 79900, stock: 2, description: 'Apple Intelligence, A18 chip, 48MP Fusion camera, Action Button, USB-C.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.1 inch', Color: 'Teal', Battery: '3561 mAh', Processor: 'A18', Camera: '48 MP Fusion', OS: 'iOS 18', Weight: '170 g', '5G': 'Yes', Warranty: '1 Year Apple India' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg'], ratings: 4.7, reviewCount: 156, isNewArrival: true, isFeatured: true, emiAvailable: true, emiStarting: 6658, exchangeAvailable: true, tags: ['5g', 'apple', 'flagship', 'ios', 'new'] },
  { name: 'Apple iPhone 17 256GB Lavender', brand: 'Apple', category: 'Mobiles', price: 89900, mrp: 89900, stock: 1, description: 'Apple iPhone 17 with A19 chip, advanced camera system, and sleek design.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.3 inch', Color: 'Lavender', Battery: '3800 mAh', Processor: 'A19 Bionic', Camera: '48 MP', OS: 'iOS 19', Weight: '175 g', '5G': 'Yes', Warranty: '1 Year Apple India' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-17.jpg'], ratings: 4.8, reviewCount: 45, isNewArrival: true, isFeatured: true, emiAvailable: true, emiStarting: 7492, exchangeAvailable: true, tags: ['5g', 'apple', 'flagship', 'ios', 'new'] },

  // ============ SAMSUNG ============
  { name: 'Samsung Galaxy F06 5G (6+128GB)', brand: 'Samsung', category: 'Mobiles', price: 10999, mrp: 13999, stock: 1, description: 'Samsung Galaxy F06 5G with MediaTek Dimensity 6300, 50MP camera, 5000mAh battery.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.7 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'MediaTek Dimensity 6300', Camera: '50 MP', OS: 'Android 14 One UI 6.1', Weight: '190 g', '5G': 'Yes', Warranty: '1 Year Samsung' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f06-5g.jpg'], ratings: 4.1, reviewCount: 55, isOnOffer: true, offerLabel: 'Festival Price', emiAvailable: true, emiStarting: 917, exchangeAvailable: true, tags: ['5g', 'samsung', 'budget', 'f-series'] },

  // ============ REALME ============
  { name: 'Realme 16 Pro+ 5G (8+128GB) Master Gold', brand: 'Realme', category: 'Mobiles', price: 22999, mrp: 25999, stock: 2, description: 'Realme 16 Pro+ 5G with Snapdragon 7s Gen 3, 108MP camera, 5200mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.7 inch', Color: 'Master Gold', Battery: '5200 mAh', Processor: 'Snapdragon 7s Gen 3', Camera: '108 MP', OS: 'Android 14 Realme UI 5.0', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-16-pro-plus.jpg'], ratings: 4.3, reviewCount: 42, isNewArrival: true, emiAvailable: true, emiStarting: 1917, exchangeAvailable: true, tags: ['5g', 'realme', 'mid-range'] },
  { name: 'Realme 16T 5G (8+128GB) Aurora Green', brand: 'Realme', category: 'Mobiles', price: 15999, mrp: 17999, stock: 1, description: 'Realme 16T 5G with Dimensity 7300 Energy, 50MP camera, 5000mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Aurora Green', Battery: '5000 mAh', Processor: 'Dimensity 7300 Energy', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '182 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-16t-5g.jpg'], ratings: 4.2, reviewCount: 30, isNewArrival: true, emiAvailable: true, emiStarting: 1333, exchangeAvailable: true, tags: ['5g', 'realme', 'mid-range'] },
  { name: 'Realme 16T 5G (8+256GB) Green', brand: 'Realme', category: 'Mobiles', price: 17999, mrp: 19999, stock: 1, description: 'Realme 16T 5G with Dimensity 7300 Energy, 50MP camera, 5000mAh battery.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.67 inch', Color: 'Green', Battery: '5000 mAh', Processor: 'Dimensity 7300 Energy', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '182 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-16t-5g.jpg'], ratings: 4.2, reviewCount: 30, isNewArrival: true, emiAvailable: true, emiStarting: 1500, exchangeAvailable: true, tags: ['5g', 'realme', 'mid-range'] },
  { name: 'Realme C83 5G (4+64GB) Blooming Purple', brand: 'Realme', category: 'Mobiles', price: 9999, mrp: 11999, stock: 1, description: 'Realme C83 5G budget smartphone with 50MP camera and 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.7 inch', Color: 'Blooming Purple', Battery: '5000 mAh', Processor: 'Unisoc T612', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-c83.jpg'], ratings: 3.9, reviewCount: 20, emiAvailable: true, emiStarting: 833, exchangeAvailable: true, tags: ['5g', 'realme', 'budget'] },
  { name: 'Realme C83 5G (4+64GB) Sprouting Green', brand: 'Realme', category: 'Mobiles', price: 9999, mrp: 11999, stock: 1, description: 'Realme C83 5G budget smartphone with 50MP camera and 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.7 inch', Color: 'Sprouting Green', Battery: '5000 mAh', Processor: 'Unisoc T612', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-c83.jpg'], ratings: 3.9, reviewCount: 20, emiAvailable: true, emiStarting: 833, exchangeAvailable: true, tags: ['5g', 'realme', 'budget'] },
  { name: 'Realme C85 (4+128GB) Parrot Purple', brand: 'Realme', category: 'Mobiles', price: 8499, mrp: 9999, stock: 1, description: 'Realme C85 with 50MP AI camera, 5000mAh battery, and sleek design.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.7 inch', Color: 'Parrot Purple', Battery: '5000 mAh', Processor: 'MediaTek Helio G85', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '188 g', '5G': 'No', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-c85.jpg'], ratings: 3.8, reviewCount: 15, emiAvailable: true, emiStarting: 708, exchangeAvailable: true, tags: ['realme', 'budget'] },
  { name: 'Realme 13 5G (8+128GB) Purple', brand: 'Realme', category: 'Mobiles', price: 16999, mrp: 19999, stock: 1, description: 'Realme 13 5G with Dimensity 6300, 50MP camera, 5000mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.72 inch', Color: 'Purple', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '190 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-13-5g.jpg'], ratings: 4.1, reviewCount: 45, emiAvailable: true, emiStarting: 1417, exchangeAvailable: true, tags: ['5g', 'realme', 'mid-range'] },
  { name: 'Realme 13+ 5G (8+128GB) Gold', brand: 'Realme', category: 'Mobiles', price: 19999, mrp: 22999, stock: 1, description: 'Realme 13+ 5G with Dimensity 7300 Energy, 50MP Sony camera, 5000mAh.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Gold', Battery: '5000 mAh', Processor: 'Dimensity 7300 Energy', Camera: '50 MP Sony', OS: 'Android 14 Realme UI 5.0', Weight: '183 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-13-plus-5g.jpg'], ratings: 4.2, reviewCount: 38, emiAvailable: true, emiStarting: 1667, exchangeAvailable: true, tags: ['5g', 'realme', 'mid-range'] },
  { name: 'Realme 14T 5G (8+128GB) Green', brand: 'Realme', category: 'Mobiles', price: 15499, mrp: 17999, stock: 1, description: 'Realme 14T 5G with powerful processor, 50MP AI camera, 5000mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Green', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-14t-5g.jpg'], ratings: 4.1, reviewCount: 25, isNewArrival: true, emiAvailable: true, emiStarting: 1292, exchangeAvailable: true, tags: ['5g', 'realme', 'mid-range'] },
  { name: 'Realme 15 Pro 5G (8+128GB) Green', brand: 'Realme', category: 'Mobiles', price: 24999, mrp: 27999, stock: 1, description: 'Realme 15 Pro 5G with Snapdragon 7s Gen 3, 108MP camera, 5200mAh.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.7 inch', Color: 'Green', Battery: '5200 mAh', Processor: 'Snapdragon 7s Gen 3', Camera: '108 MP', OS: 'Android 14 Realme UI 5.0', Weight: '182 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-15-pro.jpg'], ratings: 4.3, reviewCount: 35, isNewArrival: true, emiAvailable: true, emiStarting: 2083, exchangeAvailable: true, tags: ['5g', 'realme', 'upper-mid'] },
  { name: 'Realme 16 Pro 5G (8+256GB)', brand: 'Realme', category: 'Mobiles', price: 25999, mrp: 28999, stock: 1, description: 'Realme 16 Pro 5G flagship with Snapdragon 7s Gen 3, 108MP OIS camera.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.7 inch', Color: 'Green', Battery: '5200 mAh', Processor: 'Snapdragon 7s Gen 3', Camera: '108 MP OIS', OS: 'Android 14 Realme UI 5.0', Weight: '183 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-16-pro.jpg'], ratings: 4.4, reviewCount: 28, isNewArrival: true, isFeatured: true, emiAvailable: true, emiStarting: 2167, exchangeAvailable: true, tags: ['5g', 'realme', 'upper-mid'] },
  { name: 'Realme 8 5G (4+128GB) Cyber Black', brand: 'Realme', category: 'Mobiles', price: 12999, mrp: 15999, stock: 1, description: 'Realme 8 5G with Dimensity 700, 48MP camera, 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.5 inch', Color: 'Cyber Black', Battery: '5000 mAh', Processor: 'Dimensity 700', Camera: '48 MP', OS: 'Android 11 Realme UI 2.0', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-8-5g.jpg'], ratings: 4.0, reviewCount: 65, emiAvailable: true, emiStarting: 1083, exchangeAvailable: true, tags: ['5g', 'realme', 'budget'] },
  { name: 'Realme C71 (4+64GB)', brand: 'Realme', category: 'Mobiles', price: 6999, mrp: 8999, stock: 2, description: 'Realme C71 budget smartphone with 50MP camera, 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.7 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'Unisoc T612', Camera: '50 MP', OS: 'Android 13 Realme UI 4.0', Weight: '186 g', '5G': 'No', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-c71.jpg'], ratings: 3.7, reviewCount: 22, emiAvailable: true, emiStarting: 583, exchangeAvailable: true, tags: ['realme', 'budget'] },
  { name: 'Realme C83 5G (6+128GB) Sprouting Green', brand: 'Realme', category: 'Mobiles', price: 10999, mrp: 12999, stock: 1, description: 'Realme C83 5G with 50MP camera, 5000mAh battery, side fingerprint.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.7 inch', Color: 'Sprouting Green', Battery: '5000 mAh', Processor: 'Unisoc T612', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-c83.jpg'], ratings: 3.9, reviewCount: 20, emiAvailable: true, emiStarting: 917, exchangeAvailable: true, tags: ['5g', 'realme', 'budget'] },
  { name: 'Realme C85 5G (4+128GB)', brand: 'Realme', category: 'Mobiles', price: 9499, mrp: 11499, stock: 1, description: 'Realme C85 5G budget smartphone with 50MP AI camera, 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.7 inch', Color: 'Green', Battery: '5000 mAh', Processor: 'MediaTek Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '188 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-c85-5g.jpg'], ratings: 4.0, reviewCount: 18, emiAvailable: true, emiStarting: 792, exchangeAvailable: true, tags: ['5g', 'realme', 'budget'] },
  { name: 'Realme P4 (8+128GB) 5G', brand: 'Realme', category: 'Mobiles', price: 14999, mrp: 16999, stock: 4, description: 'Realme P4 5G with Dimensity 7300, 50MP camera, 5000mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'Dimensity 7300', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '183 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-p4.jpg'], ratings: 4.2, reviewCount: 50, isOnOffer: true, offerLabel: 'Best Seller', emiAvailable: true, emiStarting: 1250, exchangeAvailable: true, tags: ['5g', 'realme', 'mid-range'] },
  { name: 'Realme P4 Lite (4+64GB) 4G', brand: 'Realme', category: 'Mobiles', price: 8999, mrp: 10999, stock: 1, description: 'Realme P4 Lite 4G with Helio G85, 50MP camera, 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.67 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'MediaTek Helio G85', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '187 g', '5G': 'No', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-p4-lite.jpg'], ratings: 3.9, reviewCount: 30, emiAvailable: true, emiStarting: 750, exchangeAvailable: true, tags: ['realme', 'budget'] },
  { name: 'Realme P4 Lite (4+64GB) 5G Fresh', brand: 'Realme', category: 'Mobiles', price: 9999, mrp: 11999, stock: 2, description: 'Realme P4 Lite 5G with Dimensity 6300, 50MP camera, 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.67 inch', Color: 'Fresh Green', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-p4-lite-5g.jpg'], ratings: 4.0, reviewCount: 25, emiAvailable: true, emiStarting: 833, exchangeAvailable: true, tags: ['5g', 'realme', 'budget'] },
  { name: 'Realme P4 Power 5G (8+128GB) Fresh', brand: 'Realme', category: 'Mobiles', price: 13999, mrp: 15999, stock: 3, description: 'Realme P4 Power 5G with 6000mAh battery, Dimensity 7300, 50MP camera.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.72 inch', Color: 'Fresh Green', Battery: '6000 mAh', Processor: 'Dimensity 7300', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '195 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-p4-power.jpg'], ratings: 4.3, reviewCount: 40, isOnOffer: true, offerLabel: 'Long Battery', emiAvailable: true, emiStarting: 1167, exchangeAvailable: true, tags: ['5g', 'realme', 'battery', 'mid-range'] },
  { name: 'Realme P4 Power 5G (8+256GB) Trans Silver', brand: 'Realme', category: 'Mobiles', price: 15999, mrp: 17999, stock: 1, description: 'Realme P4 Power 5G with 6000mAh battery, Dimensity 7300, 50MP camera.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.72 inch', Color: 'Trans Silver', Battery: '6000 mAh', Processor: 'Dimensity 7300', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '195 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-p4-power.jpg'], ratings: 4.3, reviewCount: 40, emiAvailable: true, emiStarting: 1333, exchangeAvailable: true, tags: ['5g', 'realme', 'battery', 'mid-range'] },
  { name: 'Realme P4X (6+128GB) 5G', brand: 'Realme', category: 'Mobiles', price: 11999, mrp: 13999, stock: 2, description: 'Realme P4X 5G with Dimensity 6300, 50MP camera, 5000mAh battery.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Blue', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Realme UI 5.0', Weight: '183 g', '5G': 'Yes', Warranty: '1 Year Realme' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/realme-p4x.jpg'], ratings: 4.1, reviewCount: 35, emiAvailable: true, emiStarting: 1000, exchangeAvailable: true, tags: ['5g', 'realme', 'mid-range'] },

  // ============ OPPO ============
  { name: 'OPPO A6 Pro (8+128GB) Cappuccino Brown', brand: 'OPPO', category: 'Mobiles', price: 16999, mrp: 19999, stock: 5, description: 'OPPO A6 Pro with 50MP AI camera, 5000mAh battery, 33W SUPERVOOC charging.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Cappuccino Brown', Battery: '5000 mAh', Processor: 'Snapdragon 6 Gen 1', Camera: '50 MP', OS: 'Android 14 ColorOS 14', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-a6-pro.jpg'], ratings: 4.2, reviewCount: 45, emiAvailable: true, emiStarting: 1417, exchangeAvailable: true, tags: ['5g', 'oppo', 'mid-range'] },
  { name: 'OPPO A6X 5G (6+128GB) Olive Green', brand: 'OPPO', category: 'Mobiles', price: 13999, mrp: 16999, stock: 2, description: 'OPPO A6X 5G with 50MP camera, 5000mAh battery, 33W fast charging.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Olive Green', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 ColorOS 14', Weight: '184 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-a6x-5g.jpg'], ratings: 4.1, reviewCount: 30, emiAvailable: true, emiStarting: 1167, exchangeAvailable: true, tags: ['5g', 'oppo', 'mid-range'] },
  { name: 'OPPO A6X 5G (4+64GB) Ice Blue', brand: 'OPPO', category: 'Mobiles', price: 11999, mrp: 14999, stock: 5, description: 'OPPO A6X 5G with 50MP camera, 5000mAh battery, 33W SUPERVOOC.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.67 inch', Color: 'Ice Blue', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 ColorOS 14', Weight: '184 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-a6x-5g.jpg'], ratings: 4.0, reviewCount: 25, emiAvailable: true, emiStarting: 1000, exchangeAvailable: true, tags: ['5g', 'oppo', 'budget'] },
  { name: 'OPPO A6X 5G (4+128GB) Ice Blue', brand: 'OPPO', category: 'Mobiles', price: 12999, mrp: 15999, stock: 2, description: 'OPPO A6X 5G with 50MP camera, 5000mAh battery, 33W SUPERVOOC.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Ice Blue', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 ColorOS 14', Weight: '184 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-a6x-5g.jpg'], ratings: 4.0, reviewCount: 25, emiAvailable: true, emiStarting: 1083, exchangeAvailable: true, tags: ['5g', 'oppo', 'budget'] },
  { name: 'OPPO A6X (4+64GB) 4G Ice Blue', brand: 'OPPO', category: 'Mobiles', price: 9999, mrp: 12999, stock: 2, description: 'OPPO A6X 4G with 50MP camera, 5000mAh battery, 33W fast charging.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.67 inch', Color: 'Ice Blue', Battery: '5000 mAh', Processor: 'MediaTek Helio G85', Camera: '50 MP', OS: 'Android 14 ColorOS 14', Weight: '185 g', '5G': 'No', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-a6x.jpg'], ratings: 3.9, reviewCount: 18, emiAvailable: true, emiStarting: 833, exchangeAvailable: true, tags: ['oppo', 'budget'] },
  { name: 'OPPO A96 (8+128GB) Black', brand: 'OPPO', category: 'Mobiles', price: 15999, mrp: 19999, stock: 1, description: 'OPPO A96 with 50MP camera, 5000mAh battery, 33W SUPERVOOC charge.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.59 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'Snapdragon 680', Camera: '50 MP', OS: 'Android 11 ColorOS 11.1', Weight: '190 g', '5G': 'No', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-a96-4g.jpg'], ratings: 4.0, reviewCount: 55, emiAvailable: true, emiStarting: 1333, exchangeAvailable: true, tags: ['oppo', 'mid-range'] },
  { name: 'OPPO F33 (8+256GB) 5G', brand: 'OPPO', category: 'Mobiles', price: 22999, mrp: 25999, stock: 1, description: 'OPPO F33 5G with 108MP camera, 5000mAh battery, 67W SUPERVOOC.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.67 inch', Color: 'Green', Battery: '5000 mAh', Processor: 'Snapdragon 6 Gen 1', Camera: '108 MP', OS: 'Android 14 ColorOS 14', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-f33-5g.jpg'], ratings: 4.3, reviewCount: 40, emiAvailable: true, emiStarting: 1917, exchangeAvailable: true, tags: ['5g', 'oppo', 'camera', 'upper-mid'] },
  { name: 'OPPO F33 (8+128GB) 5G Demo', brand: 'OPPO', category: 'Mobiles', price: 19999, mrp: 22999, stock: 1, description: 'OPPO F33 5G with 108MP camera, 5000mAh battery, 67W SUPERVOOC.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Green', Battery: '5000 mAh', Processor: 'Snapdragon 6 Gen 1', Camera: '108 MP', OS: 'Android 14 ColorOS 14', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-f33-5g.jpg'], ratings: 4.3, reviewCount: 40, emiAvailable: true, emiStarting: 1667, exchangeAvailable: true, tags: ['5g', 'oppo', 'camera', 'upper-mid'] },
  { name: 'OPPO F33 Pro 5G (8+256GB)', brand: 'OPPO', category: 'Mobiles', price: 27999, mrp: 31999, stock: 5, description: 'OPPO F33 Pro 5G with 108MP OIS camera, 80W SUPERVOOC, 5000mAh.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.7 inch', Color: 'Green', Battery: '5000 mAh', Processor: 'Snapdragon 7s Gen 2', Camera: '108 MP OIS', OS: 'Android 14 ColorOS 14', Weight: '183 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-f33-pro-5g.jpg'], ratings: 4.4, reviewCount: 55, isFeatured: true, emiAvailable: true, emiStarting: 2333, exchangeAvailable: true, tags: ['5g', 'oppo', 'camera', 'flagship'] },
  { name: 'OPPO K13X 5G (8+128GB) Violet', brand: 'OPPO', category: 'Mobiles', price: 15999, mrp: 18999, stock: 1, description: 'OPPO K13X 5G with 50MP camera, 5000mAh battery, 67W fast charging.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Violet', Battery: '5000 mAh', Processor: 'Snapdragon 6 Gen 1', Camera: '50 MP', OS: 'Android 14 ColorOS 14', Weight: '184 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-k13x.jpg'], ratings: 4.2, reviewCount: 28, emiAvailable: true, emiStarting: 1333, exchangeAvailable: true, tags: ['5g', 'oppo', 'mid-range'] },
  { name: 'OPPO K14X 5G (6+128GB) Icy Blue', brand: 'OPPO', category: 'Mobiles', price: 13999, mrp: 16999, stock: 11, description: 'OPPO K14X 5G with 50MP camera, 5000mAh battery, 33W SUPERVOOC.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Icy Blue', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 ColorOS 14', Weight: '184 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-k14x.jpg'], ratings: 4.1, reviewCount: 35, isOnOffer: true, offerLabel: 'Best Value 5G', emiAvailable: true, emiStarting: 1167, exchangeAvailable: true, tags: ['5g', 'oppo', 'budget'] },
  { name: 'OPPO K14X 5G (6+128GB) Prism Violet', brand: 'OPPO', category: 'Mobiles', price: 13999, mrp: 16999, stock: 2, description: 'OPPO K14X 5G with 50MP camera, 5000mAh battery, 33W SUPERVOOC.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Prism Violet', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 ColorOS 14', Weight: '184 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-k14x.jpg'], ratings: 4.1, reviewCount: 35, emiAvailable: true, emiStarting: 1167, exchangeAvailable: true, tags: ['5g', 'oppo', 'budget'] },
  { name: 'OPPO K14 (6+128GB) 5G', brand: 'OPPO', category: 'Mobiles', price: 14999, mrp: 17999, stock: 1, description: 'OPPO K14 5G with Dimensity 7300, 50MP camera, 5000mAh battery.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Blue', Battery: '5000 mAh', Processor: 'Dimensity 7300', Camera: '50 MP', OS: 'Android 14 ColorOS 14', Weight: '183 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-k14.jpg'], ratings: 4.2, reviewCount: 30, emiAvailable: true, emiStarting: 1250, exchangeAvailable: true, tags: ['5g', 'oppo', 'mid-range'] },
  { name: 'OPPO A6S (6+128GB) Aurora Gold', brand: 'OPPO', category: 'Mobiles', price: 12999, mrp: 15999, stock: 3, description: 'OPPO A6S with 50MP AI camera, 5000mAh battery, 33W SUPERVOOC.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Aurora Gold', Battery: '5000 mAh', Processor: 'Snapdragon 680', Camera: '50 MP', OS: 'Android 13 ColorOS 13', Weight: '186 g', '5G': 'No', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-a6s.jpg'], ratings: 4.0, reviewCount: 22, emiAvailable: true, emiStarting: 1083, exchangeAvailable: true, tags: ['oppo', 'mid-range'] },
  { name: 'OPPO Reno 13 (8+128GB) Blue', brand: 'OPPO', category: 'Mobiles', price: 32999, mrp: 37999, stock: 1, description: 'OPPO Reno 13 with 50MP OIS camera, 5600mAh battery, 80W SUPERVOOC.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.59 inch', Color: 'Blue', Battery: '5600 mAh', Processor: 'Dimensity 8350', Camera: '50 MP OIS', OS: 'Android 14 ColorOS 14', Weight: '181 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-reno13.jpg'], ratings: 4.4, reviewCount: 50, emiAvailable: true, emiStarting: 2750, exchangeAvailable: true, tags: ['5g', 'oppo', 'premium'] },
  { name: 'OPPO Reno 15 Pro Mini (12+256GB) Coca Brown', brand: 'OPPO', category: 'Mobiles', price: 44999, mrp: 49999, stock: 1, description: 'OPPO Reno 15 Pro Mini with 50MP Hasselblad camera, 5700mAh, 80W.', specifications: { RAM: '12 GB', Storage: '256 GB', 'Screen Size': '6.3 inch', Color: 'Coca Brown', Battery: '5700 mAh', Processor: 'Snapdragon 8s Gen 3', Camera: '50 MP Hasselblad', OS: 'Android 15 ColorOS 15', Weight: '178 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-reno15-pro-mini.jpg'], ratings: 4.5, reviewCount: 20, isNewArrival: true, isFeatured: true, emiAvailable: true, emiStarting: 3750, exchangeAvailable: true, tags: ['5g', 'oppo', 'premium', 'new'] },
  { name: 'OPPO Reno 15C (12+256GB) Twilight Blue', brand: 'OPPO', category: 'Mobiles', price: 29999, mrp: 34999, stock: 1, description: 'OPPO Reno 15C with 50MP camera, 5000mAh battery, 67W SUPERVOOC.', specifications: { RAM: '12 GB', Storage: '256 GB', 'Screen Size': '6.67 inch', Color: 'Twilight Blue', Battery: '5000 mAh', Processor: 'Snapdragon 7s Gen 3', Camera: '50 MP', OS: 'Android 15 ColorOS 15', Weight: '182 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-reno15c.jpg'], ratings: 4.3, reviewCount: 25, isNewArrival: true, emiAvailable: true, emiStarting: 2500, exchangeAvailable: true, tags: ['5g', 'oppo', 'upper-mid'] },
  { name: 'OPPO Reno 16C 5G (8+128GB) Starry White', brand: 'OPPO', category: 'Mobiles', price: 24999, mrp: 29999, stock: 5, description: 'OPPO Reno 16C 5G with 50MP OIS, 67W SUPERVOOC, 5000mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.67 inch', Color: 'Starry White', Battery: '5000 mAh', Processor: 'Snapdragon 7s Gen 2', Camera: '50 MP OIS', OS: 'Android 14 ColorOS 14', Weight: '183 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-reno16c.jpg'], ratings: 4.3, reviewCount: 40, emiAvailable: true, emiStarting: 2083, exchangeAvailable: true, tags: ['5g', 'oppo', 'camera'] },
  { name: 'OPPO Reno 16C 5G (8+256GB) Starry White', brand: 'OPPO', category: 'Mobiles', price: 27999, mrp: 32999, stock: 2, description: 'OPPO Reno 16C 5G with 50MP OIS, 67W SUPERVOOC, 5000mAh battery.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.67 inch', Color: 'Starry White', Battery: '5000 mAh', Processor: 'Snapdragon 7s Gen 2', Camera: '50 MP OIS', OS: 'Android 14 ColorOS 14', Weight: '183 g', '5G': 'Yes', Warranty: '1 Year OPPO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/oppo-reno16c.jpg'], ratings: 4.3, reviewCount: 40, emiAvailable: true, emiStarting: 2333, exchangeAvailable: true, tags: ['5g', 'oppo', 'camera'] },

  // ============ VIVO ============
  { name: 'Vivo T4 Ultra (8+256GB)', brand: 'Vivo', category: 'Mobiles', price: 24999, mrp: 28999, stock: 1, description: 'Vivo T4 Ultra with Snapdragon 7s Gen 3, 50MP camera, 5500mAh battery.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.78 inch', Color: 'Black', Battery: '5500 mAh', Processor: 'Snapdragon 7s Gen 3', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '188 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-t4-ultra.jpg'], ratings: 4.3, reviewCount: 35, isNewArrival: true, emiAvailable: true, emiStarting: 2083, exchangeAvailable: true, tags: ['5g', 'vivo', 'upper-mid'] },
  { name: 'Vivo T5 Pro (8+256GB)', brand: 'Vivo', category: 'Mobiles', price: 22999, mrp: 26999, stock: 1, description: 'Vivo T5 Pro with Snapdragon 7 Gen 3, 50MP OIS camera, 5000mAh.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.78 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'Snapdragon 7 Gen 3', Camera: '50 MP OIS', OS: 'Android 14 Funtouch 14', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-t5-pro.jpg'], ratings: 4.3, reviewCount: 40, emiAvailable: true, emiStarting: 1917, exchangeAvailable: true, tags: ['5g', 'vivo', 'mid-range'] },
  { name: 'Vivo T4 5G (12+256GB) Blaze', brand: 'Vivo', category: 'Mobiles', price: 21999, mrp: 25999, stock: 1, description: 'Vivo T4 5G with Snapdragon 7s Gen 3, 50MP camera, 6000mAh battery.', specifications: { RAM: '12 GB', Storage: '256 GB', 'Screen Size': '6.78 inch', Color: 'Blaze', Battery: '6000 mAh', Processor: 'Snapdragon 7s Gen 3', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '190 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-t4-5g.jpg'], ratings: 4.4, reviewCount: 50, isFeatured: true, emiAvailable: true, emiStarting: 1833, exchangeAvailable: true, tags: ['5g', 'vivo', 'battery', 'mid-range'] },
  { name: 'Vivo T4 Lite 5G (4+128GB) Gold', brand: 'Vivo', category: 'Mobiles', price: 12999, mrp: 15999, stock: 2, description: 'Vivo T4 Lite 5G with Dimensity 6300, 50MP camera, 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.56 inch', Color: 'Gold', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-t4-lite.jpg'], ratings: 4.0, reviewCount: 30, emiAvailable: true, emiStarting: 1083, exchangeAvailable: true, tags: ['5g', 'vivo', 'budget'] },
  { name: 'Vivo T4R 5G (12+256GB) Blue', brand: 'Vivo', category: 'Mobiles', price: 19999, mrp: 23999, stock: 1, description: 'Vivo T4R 5G with Dimensity 7300, 50MP camera, 5500mAh battery.', specifications: { RAM: '12 GB', Storage: '256 GB', 'Screen Size': '6.78 inch', Color: 'Blue', Battery: '5500 mAh', Processor: 'Dimensity 7300', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '187 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-t4r.jpg'], ratings: 4.2, reviewCount: 35, emiAvailable: true, emiStarting: 1667, exchangeAvailable: true, tags: ['5g', 'vivo', 'mid-range'] },
  { name: 'Vivo T4X 5G (8+128GB) Fresh', brand: 'Vivo', category: 'Mobiles', price: 14999, mrp: 17999, stock: 2, description: 'Vivo T4X 5G with Dimensity 7300, 50MP camera, 6000mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.72 inch', Color: 'Fresh', Battery: '6000 mAh', Processor: 'Dimensity 7300', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '192 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-t4x.jpg'], ratings: 4.2, reviewCount: 45, isOnOffer: true, offerLabel: 'Battery King', emiAvailable: true, emiStarting: 1250, exchangeAvailable: true, tags: ['5g', 'vivo', 'battery'] },
  { name: 'Vivo T5 Pro 5G (8+128GB)', brand: 'Vivo', category: 'Mobiles', price: 19999, mrp: 23999, stock: 1, description: 'Vivo T5 Pro 5G with Snapdragon 7 Gen 3, 50MP OIS, 5000mAh.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.78 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'Snapdragon 7 Gen 3', Camera: '50 MP OIS', OS: 'Android 14 Funtouch 14', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-t5-pro.jpg'], ratings: 4.3, reviewCount: 40, emiAvailable: true, emiStarting: 1667, exchangeAvailable: true, tags: ['5g', 'vivo', 'mid-range'] },
  { name: 'Vivo T5X (8+128GB) 5G Fresh', brand: 'Vivo', category: 'Mobiles', price: 13999, mrp: 16999, stock: 10, description: 'Vivo T5X 5G with Dimensity 920, 50MP camera, 5000mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.58 inch', Color: 'Fresh', Battery: '5000 mAh', Processor: 'Dimensity 920', Camera: '50 MP', OS: 'Android 13 Funtouch 13', Weight: '187 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-t5x-5g.jpg'], ratings: 4.1, reviewCount: 65, isOnOffer: true, offerLabel: 'Hot Seller', emiAvailable: true, emiStarting: 1167, exchangeAvailable: true, tags: ['5g', 'vivo', 'mid-range'] },
  { name: 'Vivo V70 FE 5G (8+256GB)', brand: 'Vivo', category: 'Mobiles', price: 28999, mrp: 33999, stock: 3, description: 'Vivo V70 FE 5G with 50MP OIS ZEISS camera, 5500mAh, 80W FlashCharge.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.78 inch', Color: 'Gold', Battery: '5500 mAh', Processor: 'Snapdragon 7s Gen 3', Camera: '50 MP ZEISS OIS', OS: 'Android 14 Funtouch 14', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-v70-fe.jpg'], ratings: 4.4, reviewCount: 50, isFeatured: true, emiAvailable: true, emiStarting: 2417, exchangeAvailable: true, tags: ['5g', 'vivo', 'camera', 'premium'] },
  { name: 'Vivo Y05 (4+64GB) V2556', brand: 'Vivo', category: 'Mobiles', price: 8999, mrp: 11999, stock: 1, description: 'Vivo Y05 with 50MP camera, 5000mAh battery, 15W fast charging.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.56 inch', Color: 'Gold', Battery: '5000 mAh', Processor: 'MediaTek Helio G85', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '186 g', '5G': 'No', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-y05.jpg'], ratings: 3.8, reviewCount: 20, emiAvailable: true, emiStarting: 750, exchangeAvailable: true, tags: ['vivo', 'budget'] },
  { name: 'Vivo Y11 (4+128GB) 5G', brand: 'Vivo', category: 'Mobiles', price: 11999, mrp: 14999, stock: 1, description: 'Vivo Y11 5G with Dimensity 6300, 50MP camera, 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.56 inch', Color: 'Blue', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-y11-5g.jpg'], ratings: 4.0, reviewCount: 25, emiAvailable: true, emiStarting: 1000, exchangeAvailable: true, tags: ['5g', 'vivo', 'budget'] },
  { name: 'Vivo Y21 5G (4+128GB) V2553', brand: 'Vivo', category: 'Mobiles', price: 10999, mrp: 13999, stock: 1, description: 'Vivo Y21 5G with Dimensity 6300, 50MP camera, 5000mAh battery.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.56 inch', Color: 'Twinkling Blue', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-y21-5g.jpg'], ratings: 3.9, reviewCount: 30, emiAvailable: true, emiStarting: 917, exchangeAvailable: true, tags: ['5g', 'vivo', 'budget'] },
  { name: 'Vivo Y21 5G (6+128GB) V2553', brand: 'Vivo', category: 'Mobiles', price: 12499, mrp: 15499, stock: 1, description: 'Vivo Y21 5G with Dimensity 6300, 50MP camera, 5000mAh battery.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.56 inch', Color: 'Twinkling Blue', Battery: '5000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-y21-5g.jpg'], ratings: 3.9, reviewCount: 30, emiAvailable: true, emiStarting: 1042, exchangeAvailable: true, tags: ['5g', 'vivo', 'budget'] },
  { name: 'Vivo Y31 5G (6+128GB) Green', brand: 'Vivo', category: 'Mobiles', price: 14999, mrp: 17999, stock: 1, description: 'Vivo Y31 5G with Dimensity 7300, 50MP camera, 5000mAh battery.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.68 inch', Color: 'Green', Battery: '5000 mAh', Processor: 'Dimensity 7300', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '188 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-y31-5g.jpg'], ratings: 4.1, reviewCount: 25, emiAvailable: true, emiStarting: 1250, exchangeAvailable: true, tags: ['5g', 'vivo', 'mid-range'] },
  { name: 'Vivo Y35 (8+128GB) Black', brand: 'Vivo', category: 'Mobiles', price: 15999, mrp: 18999, stock: 1, description: 'Vivo Y35 with Snapdragon 680, 50MP camera, 5000mAh, 44W fast charge.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.58 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'Snapdragon 680', Camera: '50 MP', OS: 'Android 12 Funtouch 12', Weight: '188 g', '5G': 'No', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-y35-2022.jpg'], ratings: 4.0, reviewCount: 60, emiAvailable: true, emiStarting: 1333, exchangeAvailable: true, tags: ['vivo', 'mid-range'] },
  { name: 'Vivo Y51 Pro 5G (8+128GB)', brand: 'Vivo', category: 'Mobiles', price: 18999, mrp: 22999, stock: 3, description: 'Vivo Y51 Pro 5G with Dimensity 920, 64MP OIS camera, 5000mAh.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.62 inch', Color: 'Blue', Battery: '5000 mAh', Processor: 'Dimensity 920', Camera: '64 MP OIS', OS: 'Android 12 Funtouch 12', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year Vivo' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/vivo-y51-pro-5g.jpg'], ratings: 4.2, reviewCount: 45, emiAvailable: true, emiStarting: 1583, exchangeAvailable: true, tags: ['5g', 'vivo', 'camera'] },

  // ============ Xiaomi / Redmi / POCO / MI ============
  { name: 'Redmi 15 5G (8+128GB)', brand: 'Xiaomi', category: 'Mobiles', price: 14999, mrp: 17999, stock: 2, description: 'Redmi 15 5G with Snapdragon 4 Gen 2, 50MP camera, 5110mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.79 inch', Color: 'Black', Battery: '5110 mAh', Processor: 'Snapdragon 4 Gen 2', Camera: '50 MP', OS: 'Android 14 HyperOS', Weight: '188 g', '5G': 'Yes', Warranty: '1 Year Xiaomi' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/redmi-15-5g.jpg'], ratings: 4.2, reviewCount: 55, emiAvailable: true, emiStarting: 1250, exchangeAvailable: true, tags: ['5g', 'xiaomi', 'mid-range'] },
  { name: 'Redmi 15C (6+128GB) 5G', brand: 'Xiaomi', category: 'Mobiles', price: 11999, mrp: 14999, stock: 1, description: 'Redmi 15C 5G with Dimensity 6300, 50MP camera, 5160mAh battery.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.88 inch', Color: 'Black', Battery: '5160 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 HyperOS', Weight: '192 g', '5G': 'Yes', Warranty: '1 Year Xiaomi' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/redmi-15c.jpg'], ratings: 4.0, reviewCount: 30, emiAvailable: true, emiStarting: 1000, exchangeAvailable: true, tags: ['5g', 'xiaomi', 'budget'] },
  { name: 'Redmi A3X (4+64GB)', brand: 'Xiaomi', category: 'Mobiles', price: 6999, mrp: 8999, stock: 1, description: 'Redmi A3X with 8MP camera, 5000mAh battery, side fingerprint sensor.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.71 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'MediaTek Helio G36', Camera: '8 MP', OS: 'Android 13 MIUI 14', Weight: '185 g', '5G': 'No', Warranty: '1 Year Xiaomi' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/redmi-a3x.jpg'], ratings: 3.7, reviewCount: 20, emiAvailable: true, emiStarting: 583, exchangeAvailable: true, tags: ['xiaomi', 'budget'] },
  { name: 'Redmi A4 5G (4+128GB)', brand: 'Xiaomi', category: 'Mobiles', price: 8999, mrp: 10999, stock: 1, description: 'Redmi A4 5G with Snapdragon 4 Gen 2, 50MP camera, 5160mAh battery.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.88 inch', Color: 'Black', Battery: '5160 mAh', Processor: 'Snapdragon 4 Gen 2', Camera: '50 MP', OS: 'Android 14 HyperOS', Weight: '192 g', '5G': 'Yes', Warranty: '1 Year Xiaomi' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/redmi-a4-5g.jpg'], ratings: 4.0, reviewCount: 35, emiAvailable: true, emiStarting: 750, exchangeAvailable: true, tags: ['5g', 'xiaomi', 'budget'] },
  { name: 'Redmi A5 (4+128GB) 4G', brand: 'Xiaomi', category: 'Mobiles', price: 7999, mrp: 9999, stock: 1, description: 'Redmi A5 4G with 50MP camera, 5000mAh battery, affordable smartphone.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.88 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'MediaTek Helio G36', Camera: '50 MP', OS: 'Android 14 HyperOS', Weight: '190 g', '5G': 'No', Warranty: '1 Year Xiaomi' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/redmi-a5.jpg'], ratings: 3.8, reviewCount: 15, emiAvailable: true, emiStarting: 667, exchangeAvailable: true, tags: ['xiaomi', 'budget'] },
  { name: 'Redmi A7 Pro (4+64GB) 5G', brand: 'Xiaomi', category: 'Mobiles', price: 9999, mrp: 12999, stock: 1, description: 'Redmi A7 Pro 5G with Dimensity 6300, 50MP camera, 5160mAh battery.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.79 inch', Color: 'Black', Battery: '5160 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 HyperOS', Weight: '188 g', '5G': 'Yes', Warranty: '1 Year Xiaomi' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/redmi-a7-pro.jpg'], ratings: 4.0, reviewCount: 20, emiAvailable: true, emiStarting: 833, exchangeAvailable: true, tags: ['5g', 'xiaomi', 'budget'] },
  { name: 'POCO C71 (4+64GB) Gold', brand: 'POCO', category: 'Mobiles', price: 6999, mrp: 8999, stock: 2, description: 'POCO C71 with 50MP camera, 5000mAh battery, side fingerprint.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.88 inch', Color: 'Gold', Battery: '5000 mAh', Processor: 'MediaTek Helio G36', Camera: '50 MP', OS: 'Android 14 HyperOS', Weight: '190 g', '5G': 'No', Warranty: '1 Year Xiaomi' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/poco-c71.jpg'], ratings: 3.8, reviewCount: 25, emiAvailable: true, emiStarting: 583, exchangeAvailable: true, tags: ['poco', 'budget'] },
  { name: 'POCO M7 5G (8+128GB) Green', brand: 'POCO', category: 'Mobiles', price: 13999, mrp: 16999, stock: 3, description: 'POCO M7 5G with Snapdragon 4 Gen 2, 50MP camera, 5000mAh battery.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.79 inch', Color: 'Green', Battery: '5000 mAh', Processor: 'Snapdragon 4 Gen 2', Camera: '50 MP', OS: 'Android 14 HyperOS', Weight: '188 g', '5G': 'Yes', Warranty: '1 Year Xiaomi' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/poco-m7-5g.jpg'], ratings: 4.2, reviewCount: 60, isOnOffer: true, offerLabel: 'Value Champion', emiAvailable: true, emiStarting: 1167, exchangeAvailable: true, tags: ['5g', 'poco', 'mid-range'] },
  { name: 'Xiaomi 11T Pro (12+256GB) Celestial Magic', brand: 'Xiaomi', category: 'Mobiles', price: 32999, mrp: 43999, stock: 1, description: 'Xiaomi 11T Pro with Snapdragon 888, 108MP camera, 120W HyperCharge.', specifications: { RAM: '12 GB', Storage: '256 GB', 'Screen Size': '6.67 inch', Color: 'Celestial Magic', Battery: '5000 mAh', Processor: 'Snapdragon 888', Camera: '108 MP', OS: 'Android 12 MIUI 13', Weight: '204 g', '5G': 'Yes', Warranty: '1 Year Xiaomi' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/xiaomi-11t-pro-5g.jpg'], ratings: 4.4, reviewCount: 80, emiAvailable: true, emiStarting: 2750, exchangeAvailable: true, tags: ['5g', 'xiaomi', 'flagship'] },

  // ============ MOTOROLA ============
  { name: 'Motorola A10 Feature Phone', brand: 'Motorola', category: 'Mobiles', price: 1299, mrp: 1799, stock: 1, description: 'Motorola A10 feature phone with dual SIM, long battery life, wireless FM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.8 inch', Color: 'Black', Battery: '1000 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '85 g', '5G': 'No', Warranty: '1 Year Motorola' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/motorola-a10.jpg'], ratings: 3.5, reviewCount: 10, tags: ['motorola', 'feature-phone'] },
  { name: 'Motorola Edge 50 Pro (12+256GB) Luxe Lavender', brand: 'Motorola', category: 'Mobiles', price: 32999, mrp: 39999, stock: 1, description: 'Motorola Edge 50 Pro with 50MP OIS camera, 125W TurboPower, pOLED display.', specifications: { RAM: '12 GB', Storage: '256 GB', 'Screen Size': '6.7 inch', Color: 'Luxe Lavender', Battery: '4500 mAh', Processor: 'Snapdragon 7 Gen 3', Camera: '50 MP OIS', OS: 'Android 14 Hello UI', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year Motorola' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-50-pro.jpg'], ratings: 4.4, reviewCount: 55, isFeatured: true, emiAvailable: true, emiStarting: 2750, exchangeAvailable: true, tags: ['5g', 'motorola', 'premium'] },
  { name: 'Motorola Edge 70 (8+256GB) 5G', brand: 'Motorola', category: 'Mobiles', price: 29999, mrp: 34999, stock: 1, description: 'Motorola Edge 70 5G with 50MP OIS, 68W TurboPower, pOLED 120Hz display.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.7 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'Snapdragon 7s Gen 3', Camera: '50 MP OIS', OS: 'Android 15 Hello UI', Weight: '185 g', '5G': 'Yes', Warranty: '1 Year Motorola' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-70.jpg'], ratings: 4.3, reviewCount: 25, isNewArrival: true, emiAvailable: true, emiStarting: 2500, exchangeAvailable: true, tags: ['5g', 'motorola', 'upper-mid'] },
  { name: 'Motorola G57 Power (8+128GB) 5G', brand: 'Motorola', category: 'Mobiles', price: 14999, mrp: 18999, stock: 3, description: 'Motorola G57 Power 5G with 6000mAh battery, 50MP camera, 33W charging.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.56 inch', Color: 'Black', Battery: '6000 mAh', Processor: 'Snapdragon 480+ 5G', Camera: '50 MP', OS: 'Android 12 My UX', Weight: '198 g', '5G': 'Yes', Warranty: '1 Year Motorola' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/motorola-g57-power.jpg'], ratings: 4.1, reviewCount: 45, emiAvailable: true, emiStarting: 1250, exchangeAvailable: true, tags: ['5g', 'motorola', 'battery'] },

  // ============ NOKIA ============
  { name: 'Nokia 105 Dual SIM', brand: 'Nokia', category: 'Mobiles', price: 1299, mrp: 1699, stock: 12, description: 'Nokia 105 dual SIM feature phone with LED torch, long battery life, wireless FM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '800 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'Nokia Series 30+', Weight: '70 g', '5G': 'No', Warranty: '1 Year Nokia' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nokia-105-4g-2023.jpg'], ratings: 3.8, reviewCount: 45, tags: ['nokia', 'feature-phone'] },
  { name: 'Nokia 105 Plus Single SIM', brand: 'Nokia', category: 'Mobiles', price: 1199, mrp: 1499, stock: 1, description: 'Nokia 105 Plus with compact design, wireless FM, LED torch, long battery.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '800 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'Nokia Series 30+', Weight: '68 g', '5G': 'No', Warranty: '1 Year Nokia' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nokia-105-plus.jpg'], ratings: 3.7, reviewCount: 15, tags: ['nokia', 'feature-phone'] },
  { name: 'Nokia 106 Dual SIM MP3', brand: 'Nokia', category: 'Mobiles', price: 1599, mrp: 1999, stock: 5, description: 'Nokia 106 with MP3 player, wireless FM, dual SIM, LED torch.', specifications: { RAM: 'N/A', Storage: '4 MB', 'Screen Size': '1.8 inch', Color: 'Black', Battery: '1000 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'Nokia Series 30+', Weight: '74 g', '5G': 'No', Warranty: '1 Year Nokia' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nokia-106-4g.jpg'], ratings: 3.8, reviewCount: 30, tags: ['nokia', 'feature-phone'] },
  { name: 'Nokia 130 Dual SIM', brand: 'Nokia', category: 'Mobiles', price: 1499, mrp: 1999, stock: 10, description: 'Nokia 130 dual SIM with big battery, wireless FM, LED torch, MP3 player.', specifications: { RAM: 'N/A', Storage: '4 MB', 'Screen Size': '1.8 inch', Color: 'Black', Battery: '1020 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'Nokia Series 30+', Weight: '75 g', '5G': 'No', Warranty: '1 Year Nokia' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nokia-130-2017.jpg'], ratings: 3.8, reviewCount: 35, tags: ['nokia', 'feature-phone'] },
  { name: 'Nokia C30 (4+64GB) Green', brand: 'Nokia', category: 'Mobiles', price: 8999, mrp: 11999, stock: 1, description: 'Nokia C30 with 6000mAh battery, 13MP camera, Android 11 Go.', specifications: { RAM: '4 GB', Storage: '64 GB', 'Screen Size': '6.82 inch', Color: 'Green', Battery: '6000 mAh', Processor: 'Unisoc SC9863A1', Camera: '13 MP', OS: 'Android 11 Go', Weight: '220 g', '5G': 'No', Warranty: '1 Year Nokia' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nokia-c30.jpg'], ratings: 3.6, reviewCount: 25, tags: ['nokia', 'budget', 'battery'] },
  { name: 'Nokia N105 Dual SIM', brand: 'Nokia', category: 'Mobiles', price: 1399, mrp: 1799, stock: 5, description: 'Nokia N105 dual SIM with LED torch, wireless FM, long-lasting battery.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '800 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'Nokia Series 30+', Weight: '70 g', '5G': 'No', Warranty: '1 Year Nokia' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nokia-105-4g-2023.jpg'], ratings: 3.8, reviewCount: 20, tags: ['nokia', 'feature-phone'] },
  { name: 'Nokia N105 Single SIM', brand: 'Nokia', category: 'Mobiles', price: 1199, mrp: 1499, stock: 2, description: 'Nokia N105 single SIM with LED torch, wireless FM, big battery.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '800 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'Nokia Series 30+', Weight: '70 g', '5G': 'No', Warranty: '1 Year Nokia' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nokia-105-4g-2023.jpg'], ratings: 3.8, reviewCount: 20, tags: ['nokia', 'feature-phone'] },
  { name: 'Nokia N150 Dual SIM', brand: 'Nokia', category: 'Mobiles', price: 1599, mrp: 1999, stock: 2, description: 'Nokia N150 dual SIM with big screen, wireless FM, LED torch, long battery.', specifications: { RAM: 'N/A', Storage: '4 MB', 'Screen Size': '2.4 inch', Color: 'Black', Battery: '1450 mAh', Processor: 'N/A', Camera: 'VGA', OS: 'Nokia Series 30+', Weight: '88 g', '5G': 'No', Warranty: '1 Year Nokia' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nokia-150-2023.jpg'], ratings: 3.7, reviewCount: 15, tags: ['nokia', 'feature-phone'] },

  // ============ HMD ============
  { name: 'HMD 100 Dual SIM', brand: 'HMD', category: 'Mobiles', price: 1499, mrp: 1999, stock: 10, description: 'HMD 100 feature phone with dual SIM, LED torch, wireless FM, big battery.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '2.0 inch', Color: 'Black', Battery: '1000 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'Nokia Series 30+', Weight: '80 g', '5G': 'No', Warranty: '1 Year HMD' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/hmd-100.jpg'], ratings: 3.6, reviewCount: 12, tags: ['hmd', 'feature-phone'] },
  { name: 'HMD 105 4G Dual SIM (Nokia)', brand: 'HMD', category: 'Mobiles', price: 1999, mrp: 2499, stock: 1, description: 'HMD 105 4G with 4G VoLTE, WhatsApp, wireless FM, LED torch.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '2.4 inch', Color: 'Black', Battery: '1450 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'Nokia Series 30+', Weight: '88 g', '5G': 'No', Warranty: '1 Year HMD' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/hmd-105-4g.jpg'], ratings: 3.7, reviewCount: 8, tags: ['hmd', 'feature-phone', '4g'] },

  // ============ LAVA ============
  { name: 'Lava A1 2020 Basic Phone', brand: 'Lava', category: 'Mobiles', price: 899, mrp: 1199, stock: 4, description: 'Lava A1 2020 feature phone with dual SIM, LED torch, wireless FM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '1000 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '75 g', '5G': 'No', Warranty: '1 Year Lava' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/lava-a1.jpg'], ratings: 3.5, reviewCount: 10, tags: ['lava', 'feature-phone'] },
  { name: 'Lava A1 Josh 2021', brand: 'Lava', category: 'Mobiles', price: 899, mrp: 1199, stock: 4, description: 'Lava A1 Josh 2021 with dual SIM, LED torch, wireless FM, big battery.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '1000 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '75 g', '5G': 'No', Warranty: '1 Year Lava' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/lava-a1-josh-2021.jpg'], ratings: 3.5, reviewCount: 10, tags: ['lava', 'feature-phone'] },
  { name: 'Lava A1 Josh 2024 Feature Phone', brand: 'Lava', category: 'Mobiles', price: 999, mrp: 1299, stock: 4, description: 'Lava A1 Josh 2024 with dual SIM, LED torch, wireless FM, UPI support.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '1000 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '78 g', '5G': 'No', Warranty: '1 Year Lava' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/lava-a1-josh-2024.jpg'], ratings: 3.6, reviewCount: 15, tags: ['lava', 'feature-phone'] },
  { name: 'Lava Hero Shakti 2025 Feature Phone', brand: 'Lava', category: 'Mobiles', price: 1099, mrp: 1499, stock: 1, description: 'Lava Hero Shakti 2025 with big battery, LED torch, wireless FM, dual SIM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.8 inch', Color: 'Black', Battery: '1200 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '80 g', '5G': 'No', Warranty: '1 Year Lava' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/lava-hero-shakti.jpg'], ratings: 3.6, reviewCount: 8, tags: ['lava', 'feature-phone'] },
  { name: 'Lava Hero 1800 Feature Phone', brand: 'Lava', category: 'Mobiles', price: 999, mrp: 1299, stock: 1, description: 'Lava Hero 1800 with big battery, dual SIM, LED torch, wireless FM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.8 inch', Color: 'Black', Battery: '1800 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '85 g', '5G': 'No', Warranty: '1 Year Lava' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/lava-hero-1800.jpg'], ratings: 3.5, reviewCount: 10, tags: ['lava', 'feature-phone'] },
  { name: 'Lava A1 Josh Mobile', brand: 'Lava', category: 'Mobiles', price: 899, mrp: 1199, stock: 9, description: 'Lava A1 Josh with dual SIM, LED torch, wireless FM, big battery.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '1000 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '75 g', '5G': 'No', Warranty: '1 Year Lava' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/lava-a1-josh.jpg'], ratings: 3.5, reviewCount: 10, tags: ['lava', 'feature-phone'] },
  { name: 'Lava Hero Shakti 2026', brand: 'Lava', category: 'Mobiles', price: 1199, mrp: 1599, stock: 8, description: 'Lava Hero Shakti 2026 with big battery, dual SIM, LED torch, wireless FM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.8 inch', Color: 'Black', Battery: '1200 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '80 g', '5G': 'No', Warranty: '1 Year Lava' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/lava-hero-shakti-2026.jpg'], ratings: 3.6, reviewCount: 12, tags: ['lava', 'feature-phone'] },

  // ============ AI+ ============
  { name: 'AI+ Nova 2 Ultra (8+128GB) Purple', brand: 'AI+', category: 'Mobiles', price: 11999, mrp: 14999, stock: 2, description: 'AI+ Nova 2 Ultra with 50MP camera, 5000mAh battery, AI features.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.56 inch', Color: 'Purple', Battery: '5000 mAh', Processor: 'Unisoc T616', Camera: '50 MP', OS: 'Android 13', Weight: '185 g', '5G': 'No', Warranty: '1 Year AI+' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/ai-nova-2-ultra.jpg'], ratings: 3.7, reviewCount: 15, emiAvailable: true, emiStarting: 1000, exchangeAvailable: true, tags: ['ai+', 'budget'] },
  { name: 'AI+ Pulse (6+128GB)', brand: 'AI+', category: 'Mobiles', price: 8999, mrp: 11999, stock: 1, description: 'AI+ Pulse with 50MP camera, 5000mAh battery, AI-powered features.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.56 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'Unisoc T612', Camera: '50 MP', OS: 'Android 13', Weight: '183 g', '5G': 'No', Warranty: '1 Year AI+' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/ai-pulse.jpg'], ratings: 3.6, reviewCount: 10, emiAvailable: true, emiStarting: 750, exchangeAvailable: true, tags: ['ai+', 'budget'] },
  { name: 'AI+ Pulse 2 (4+128GB) Blue', brand: 'AI+', category: 'Mobiles', price: 7999, mrp: 10999, stock: 1, description: 'AI+ Pulse 2 with 50MP camera, 5000mAh battery, affordable smartphone.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.56 inch', Color: 'Blue', Battery: '5000 mAh', Processor: 'Unisoc T612', Camera: '50 MP', OS: 'Android 13', Weight: '182 g', '5G': 'No', Warranty: '1 Year AI+' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/ai-pulse-2.jpg'], ratings: 3.5, reviewCount: 8, emiAvailable: true, emiStarting: 667, exchangeAvailable: true, tags: ['ai+', 'budget'] },
  { name: 'AI+ Pulse 2 (4+128GB)', brand: 'AI+', category: 'Mobiles', price: 7999, mrp: 10999, stock: 2, description: 'AI+ Pulse 2 with 50MP camera, 5000mAh battery, affordable smartphone.', specifications: { RAM: '4 GB', Storage: '128 GB', 'Screen Size': '6.56 inch', Color: 'Black', Battery: '5000 mAh', Processor: 'Unisoc T612', Camera: '50 MP', OS: 'Android 13', Weight: '182 g', '5G': 'No', Warranty: '1 Year AI+' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/ai-pulse-2.jpg'], ratings: 3.5, reviewCount: 8, emiAvailable: true, emiStarting: 667, exchangeAvailable: true, tags: ['ai+', 'budget'] },

  // ============ NOTHING ============
  { name: 'Nothing Phone (2a) Plus (8+128GB) 5G', brand: 'Nothing', category: 'Mobiles', price: 26999, mrp: 29999, stock: 1, description: 'Nothing Phone (2a) Plus with Dimensity 7350 Pro, 50MP camera, Glyph Interface.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.7 inch', Color: 'Gray', Battery: '5000 mAh', Processor: 'Dimensity 7350 Pro', Camera: '50 MP', OS: 'Android 14 Nothing OS 2.6', Weight: '190 g', '5G': 'Yes', Warranty: '1 Year Nothing' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a-plus.jpg'], ratings: 4.4, reviewCount: 45, isNewArrival: true, isFeatured: true, emiAvailable: true, emiStarting: 2250, exchangeAvailable: true, tags: ['5g', 'nothing', 'unique'] },
  { name: 'Nothing Phone 3a Lite (8+128GB) 5G', brand: 'Nothing', category: 'Mobiles', price: 22999, mrp: 25999, stock: 1, description: 'Nothing Phone 3a Lite with 50MP camera, Glyph Interface, clean Nothing OS.', specifications: { RAM: '8 GB', Storage: '128 GB', 'Screen Size': '6.7 inch', Color: 'White', Battery: '5000 mAh', Processor: 'Snapdragon 6s Gen 3', Camera: '50 MP', OS: 'Android 14 Nothing OS', Weight: '188 g', '5G': 'Yes', Warranty: '1 Year Nothing' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-3a-lite.jpg'], ratings: 4.3, reviewCount: 30, isNewArrival: true, emiAvailable: true, emiStarting: 1917, exchangeAvailable: true, tags: ['5g', 'nothing', 'unique'] },

  // ============ IQOO / IQ ============
  { name: 'iQOO Neo 10 (8+256GB)', brand: 'iQOO', category: 'Mobiles', price: 29999, mrp: 34999, stock: 3, description: 'iQOO Neo 10 with Snapdragon 8s Gen 3, 50MP OIS, 6000mAh battery.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.78 inch', Color: 'Black', Battery: '6000 mAh', Processor: 'Snapdragon 8s Gen 3', Camera: '50 MP OIS', OS: 'Android 14 Funtouch 14', Weight: '190 g', '5G': 'Yes', Warranty: '1 Year iQOO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/iqoo-neo-10.jpg'], ratings: 4.5, reviewCount: 60, isFeatured: true, emiAvailable: true, emiStarting: 2500, exchangeAvailable: true, tags: ['5g', 'iqoo', 'performance'] },
  { name: 'iQOO Z10R (8+256GB) 5G Fresh', brand: 'iQOO', category: 'Mobiles', price: 17999, mrp: 21999, stock: 1, description: 'iQOO Z10R 5G with Dimensity 7300, 50MP camera, 5500mAh battery.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.78 inch', Color: 'Fresh Green', Battery: '5500 mAh', Processor: 'Dimensity 7300', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '187 g', '5G': 'Yes', Warranty: '1 Year iQOO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/iqoo-z10r.jpg'], ratings: 4.2, reviewCount: 30, emiAvailable: true, emiStarting: 1500, exchangeAvailable: true, tags: ['5g', 'iqoo', 'mid-range'] },
  { name: 'iQOO Z10X 5G (6+128GB) Fresh', brand: 'iQOO', category: 'Mobiles', price: 13999, mrp: 16999, stock: 1, description: 'iQOO Z10X 5G with Dimensity 6300, 50MP camera, 6000mAh battery.', specifications: { RAM: '6 GB', Storage: '128 GB', 'Screen Size': '6.72 inch', Color: 'Fresh', Battery: '6000 mAh', Processor: 'Dimensity 6300', Camera: '50 MP', OS: 'Android 14 Funtouch 14', Weight: '190 g', '5G': 'Yes', Warranty: '1 Year iQOO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/iqoo-z10x.jpg'], ratings: 4.1, reviewCount: 25, emiAvailable: true, emiStarting: 1167, exchangeAvailable: true, tags: ['5g', 'iqoo', 'budget'] },
  { name: 'iQOO Z11X 5G (8+256GB) Fresh', brand: 'iQOO', category: 'Mobiles', price: 19999, mrp: 23999, stock: 1, description: 'iQOO Z11X 5G with Snapdragon 7s Gen 3, 50MP OIS, 5500mAh battery.', specifications: { RAM: '8 GB', Storage: '256 GB', 'Screen Size': '6.78 inch', Color: 'Fresh', Battery: '5500 mAh', Processor: 'Snapdragon 7s Gen 3', Camera: '50 MP OIS', OS: 'Android 14 Funtouch 14', Weight: '186 g', '5G': 'Yes', Warranty: '1 Year iQOO' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/iqoo-z11x.jpg'], ratings: 4.3, reviewCount: 25, isNewArrival: true, emiAvailable: true, emiStarting: 1667, exchangeAvailable: true, tags: ['5g', 'iqoo', 'mid-range'] },

  // ============ KARA ============
  { name: 'Kara K-1702 Feature Phone', brand: 'Kara', category: 'Mobiles', price: 599, mrp: 799, stock: 54, description: 'Kara K-1702 basic feature phone with dual SIM, LED torch, wireless FM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '800 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '65 g', '5G': 'No', Warranty: '6 Months' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/kara-k1702.jpg'], ratings: 3.3, reviewCount: 25, tags: ['kara', 'feature-phone'] },

  // ============ KARBAN ============
  { name: 'Karban K109 Star', brand: 'Karban', category: 'Mobiles', price: 699, mrp: 999, stock: 2, description: 'Karban K109 Star feature phone with dual SIM, LED torch, wireless FM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '800 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '68 g', '5G': 'No', Warranty: '6 Months' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/karban-k109.jpg'], ratings: 3.3, reviewCount: 5, tags: ['karban', 'feature-phone'] },
  { name: 'Karban K140 Pop', brand: 'Karban', category: 'Mobiles', price: 799, mrp: 1099, stock: 1, description: 'Karban K140 Pop feature phone with big battery, LED torch, dual SIM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.8 inch', Color: 'Black', Battery: '1000 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '72 g', '5G': 'No', Warranty: '6 Months' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/karban-k140.jpg'], ratings: 3.3, reviewCount: 5, tags: ['karban', 'feature-phone'] },
  { name: 'Karban K59 Star', brand: 'Karban', category: 'Mobiles', price: 699, mrp: 999, stock: 1, description: 'Karban K59 Star with dual SIM, LED torch, wireless FM, big battery.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '800 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '66 g', '5G': 'No', Warranty: '6 Months' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/karban-k59.jpg'], ratings: 3.3, reviewCount: 5, tags: ['karban', 'feature-phone'] },
  { name: 'Karban K8 Power', brand: 'Karban', category: 'Mobiles', price: 899, mrp: 1199, stock: 1, description: 'Karban K8 Power with big battery, dual SIM, LED torch, wireless FM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.8 inch', Color: 'Black', Battery: '1200 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '75 g', '5G': 'No', Warranty: '6 Months' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/karban-k8-power.jpg'], ratings: 3.3, reviewCount: 5, tags: ['karban', 'feature-phone'] },
  { name: 'Karban K9 Mini', brand: 'Karban', category: 'Mobiles', price: 699, mrp: 999, stock: 6, description: 'Karban K9 Mini compact feature phone with dual SIM, LED torch.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.44 inch', Color: 'Black', Battery: '600 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '55 g', '5G': 'No', Warranty: '6 Months' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/karban-k9-mini.jpg'], ratings: 3.2, reviewCount: 5, tags: ['karban', 'feature-phone'] },
  { name: 'Karban K9', brand: 'Karban', category: 'Mobiles', price: 799, mrp: 1099, stock: 1, description: 'Karban K9 feature phone with dual SIM, LED torch, wireless FM.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '800 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '68 g', '5G': 'No', Warranty: '6 Months' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/karban-k9.jpg'], ratings: 3.3, reviewCount: 5, tags: ['karban', 'feature-phone'] },

  // ============ I CALL ============
  { name: 'I Call C2 Hiicell', brand: 'I Call', category: 'Mobiles', price: 799, mrp: 1199, stock: 21, description: 'I Call C2 Hiicell feature phone with dual SIM, LED torch, big battery.', specifications: { RAM: 'N/A', Storage: 'N/A', 'Screen Size': '1.77 inch', Color: 'Black', Battery: '1000 mAh', Processor: 'N/A', Camera: 'N/A', OS: 'N/A', Weight: '70 g', '5G': 'No', Warranty: '6 Months' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/i-call-c2.jpg'], ratings: 3.2, reviewCount: 10, tags: ['i call', 'feature-phone'] },

  // ============ Home Appliances ============
  { name: 'Samsung 20L Microwave Oven MS20A', brand: 'Samsung', category: 'Home Appliances', price: 7490, mrp: 8999, stock: 3, description: 'Samsung 20L Solo Microwave Oven with 3 power levels, eco mode, child lock.', specifications: { Capacity: '20 Litres', Power: '700 Watts', 'Cooking Modes': 'Solo', Color: 'Black', Warranty: '1 Year Samsung', Weight: '11 kg' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/samsung-mw-ms20a.jpg'], ratings: 4.1, reviewCount: 120, isFeatured: true, emiAvailable: true, emiStarting: 625, tags: ['samsung', 'microwave', 'kitchen'] },
  { name: 'IFB 6.5 kg Fully-Automatic Washing Machine', brand: 'IFB', category: 'Home Appliances', price: 24990, mrp: 30990, stock: 2, description: 'IFB 6.5 kg Front Load Washing Machine with Triadic Wash, Deep Clean, Aqua Energie.', specifications: { Capacity: '6.5 kg', Type: 'Front Load', 'Spin Speed': '1400 RPM', Color: 'White', Warranty: '4 Years IFB', Weight: '78 kg' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/ifb-fla65-1.jpg'], ratings: 4.3, reviewCount: 85, isFeatured: true, emiAvailable: true, emiStarting: 2083, tags: ['ifb', 'washing-machine', 'laundry'] },
  { name: 'Voltas 1.5 Ton 3 Star Split AC 183V_CZT', brand: 'Voltas', category: 'Home Appliances', price: 32990, mrp: 41990, stock: 2, description: 'Voltas 1.5 Ton 3 Star Inverter Split AC with copper condenser, turbo mode, dry mode.', specifications: { Capacity: '1.5 Ton', 'Energy Rating': '3 Star', Type: 'Split Inverter', Color: 'White', Warranty: '1 Year + 5 Compressor', Weight: '42 kg' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/voltas-1-5-ton-split-ac.jpg'], ratings: 4.0, reviewCount: 65, isFeatured: true, emiAvailable: true, emiStarting: 2750, tags: ['voltas', 'ac', 'cooling'] },
  { name: 'Havells Velocity Neo 1200mm Ceiling Fan', brand: 'Havells', category: 'Home Appliances', price: 1999, mrp: 2499, stock: 10, description: 'Havells Velocity Neo 1200mm ceiling fan with high air delivery, double ball bearing motor.', specifications: { Type: 'Ceiling Fan', 'Sweep Size': '1200 mm', 'Speed': '380 RPM', Color: 'Pearl White', Warranty: '2 Years Havells', Weight: '4.2 kg' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/havells-velocity-neo.jpg'], ratings: 4.2, reviewCount: 200, tags: ['havells', 'fan', 'cooling'] },
  { name: 'Bajaj Majesty RCX 5 Oven Toaster Griller', brand: 'Bajaj', category: 'Home Appliances', price: 3499, mrp: 4499, stock: 4, description: 'Bajaj Majesty RCX 5 OTG with 52 litre capacity, motorised rotisserie, 60 min timer.', specifications: { Capacity: '52 Litres', Power: '2000 Watts', Type: 'OTG', Color: 'Silver & Black', Warranty: '2 Years Bajaj', Weight: '12 kg' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/bajaj-majesty-rcx5.jpg'], ratings: 4.1, reviewCount: 70, emiAvailable: true, emiStarting: 292, tags: ['bajaj', 'otg', 'kitchen'] },
  { name: 'Crompton Silent Pro Ceiling Fan 1200mm', brand: 'Crompton', category: 'Home Appliances', price: 3299, mrp: 4199, stock: 5, description: 'Crompton Silent Pro 1200mm BLDC motor ceiling fan with remote, 5 star energy rating.', specifications: { Type: 'Ceiling Fan', 'Sweep Size': '1200 mm', 'Speed': '360 RPM', Color: 'Pearl White', Warranty: '2 Years Crompton', Weight: '4.5 kg' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/crompton-silent-pro.jpg'], ratings: 4.3, reviewCount: 150, tags: ['crompton', 'fan', 'bldc'] },

  // ============ Furniture ============
  { name: 'Wipro Furniture 4 Seater Dining Table Set', brand: 'Wipro Furniture', category: 'Furniture', price: 15999, mrp: 21999, stock: 2, description: 'Wipro 4 Seater Solid Wood Dining Table Set with 4 chairs, teak finish, scratch-resistant.', specifications: { Material: 'Solid Sheesham Wood', Seats: '4 Seater', Finish: 'Teak', 'Table Dimensions': '120x75x75 cm', Weight: '45 kg', Warranty: '1 Year Wipro' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/wipro-4-seater-dining.jpg'], ratings: 4.2, reviewCount: 45, isFeatured: true, emiAvailable: true, emiStarting: 1334, tags: ['dining-table', 'wood', 'kitchen-furniture'] },
  { name: 'Godrej Interio Classic King Bed with Storage', brand: 'Godrej Interio', category: 'Furniture', price: 22999, mrp: 29999, stock: 1, description: 'Godrej Interio Classic King Bed with hydraulic storage, engineered wood, honey finish.', specifications: { Material: 'Engineered Wood', Size: 'King (78x72 inch)', Finish: 'Honey', Storage: 'Hydraulic', Weight: '85 kg', Warranty: '3 Years Godrej' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/godrej-classic-king-bed.jpg'], ratings: 4.4, reviewCount: 78, isFeatured: true, emiAvailable: true, emiStarting: 1917, tags: ['bed', 'king', 'bedroom'] },
  { name: 'Nilkamal Freedom Fruity Chair Set of 4', brand: 'Nilkamal', category: 'Furniture', price: 4999, mrp: 6999, stock: 8, description: 'Nilkamal Freedom Fruity Plastic Chair Set of 4, UV stabilized, stackable design.', specifications: { Material: 'Plastic (Polypropylene)', Seats: '4 Chairs', Color: 'Multi Color', Weight: '4 kg each', Stackable: 'Yes', Warranty: '1 Year Nilkamal' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/nilkamal-fruity-chair.jpg'], ratings: 3.9, reviewCount: 310, tags: ['chairs', 'plastic', 'garden'] },
  { name: 'HomeTown 3 Seater Sofa with Cushions', brand: 'HomeTown', category: 'Furniture', price: 18999, mrp: 25999, stock: 2, description: 'HomeTown 3 Seater Fabric Sofa with high-density foam cushions, solid wood frame.', specifications: { Material: 'Fabric & Solid Wood', Seats: '3 Seater', Color: 'Grey', 'Seat Height': '18 inch', Weight: '55 kg', Warranty: '1 Year HomeTown' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/hometown-3-seater-sofa.jpg'], ratings: 4.1, reviewCount: 60, isFeatured: true, emiAvailable: true, emiStarting: 1584, tags: ['sofa', 'living-room', 'fabric'] },
  { name: 'IKEA MALM 6-Drawer Dresser', brand: 'IKEA', category: 'Furniture', price: 12990, mrp: 16990, stock: 3, description: 'IKEA MALM 6-Drawer Dresser with smooth-running drawers, white stained oak effect.', specifications: { Material: 'Particleboard', Drawers: '6', Finish: 'White Stained Oak', Dimensions: '160x48x78 cm', Weight: '50 kg', Warranty: '10 Years IKEA' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/ikea-malm-dresser.jpg'], ratings: 4.3, reviewCount: 220, tags: ['dresser', 'bedroom', 'storage'] },
  { name: 'Featherlite Study Table with Shelf', brand: 'Featherlite', category: 'Furniture', price: 7999, mrp: 10999, stock: 4, description: 'Featherlite Study Table with built-in shelf, powder-coated metal frame, engineered wood top.', specifications: { Material: 'Engineered Wood & Metal', Dimensions: '120x60x75 cm', Finish: 'Walnut', 'Load Capacity': '50 kg', Weight: '25 kg', Warranty: '3 Years Featherlite' }, images: ['https://fdn2.gsmarena.com/vv/bigpic/featherlite-study-table.jpg'], ratings: 4.0, reviewCount: 95, tags: ['study-table', 'office', 'work-from-home'] },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await Product.deleteMany({});
    console.log('Cleared existing products');

    const inserted = await Product.insertMany(products);
    console.log(`Seeded ${inserted.length} products`);

    const existingUsers = await User.countDocuments();
    if (existingUsers === 0) {
      const salt = await bcrypt.genSalt(10);
      await User.insertMany([
        { name: 'Admin', phone: '9999999999', password: await bcrypt.hash('admin123', salt), role: 'admin' },
        { name: 'Employee', phone: '8888888888', password: await bcrypt.hash('emp123', salt), role: 'employee' },
        { name: 'Customer', phone: '7777777777', password: await bcrypt.hash('cust123', salt), role: 'customer' },
      ]);
      console.log('Created default users');
    }

    console.log('Seeding complete!');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

seed();
