import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from './models/Product.js';

dotenv.config();

const U = id => `https://images.unsplash.com/${id}?w=600&q=80&auto=format&fit=crop`;

const products = [
  // ============ TELEVISIONS ============
  { name: 'Samsung 55" Crystal 4K UHD Smart TV', brand: 'Samsung', category: 'Electronics', price: 46990, mrp: 59990, stock: 5, description: '55" Crystal 4K UHD display, Tizen smart TV, built-in Alexa, sleek airslim design with Dolby Audio.', specifications: { 'Screen Size': '55 inch', Resolution: '4K UHD 3840x2160', 'Display Type': 'Crystal 4K', 'Refresh Rate': '60 Hz', 'Smart TV': 'Tizen', Audio: '20W Dolby Audio', 'HDMI Ports': '3', 'USB Ports': '2', Weight: '18.2 kg', Warranty: '1 Year Samsung' }, images: [U('photo-1593359677879-a4bb92f829d1')], ratings: 4.5, reviewCount: 120, isFeatured: true, emiAvailable: true, emiStarting: 3916, tags: ['tv', 'samsung', '4k', 'smart'] },
  { name: 'LG 50" 4K UHD Smart LED TV', brand: 'LG', category: 'Electronics', price: 39990, mrp: 54990, stock: 4, description: 'LG 50" 4K UHD Smart LED TV with webOS, ThinQ AI, HDR10 Pro and sleek thin bezel design.', specifications: { 'Screen Size': '50 inch', Resolution: '4K UHD 3840x2160', 'Display Type': 'LED', 'Refresh Rate': '60 Hz', 'Smart TV': 'webOS 23', Audio: '20W', 'HDMI Ports': '3', 'USB Ports': '2', Warranty: '1 Year LG' }, images: [U('photo-1593359677879-a4bb92f829d1')], ratings: 4.4, reviewCount: 85, emiAvailable: true, emiStarting: 3333, tags: ['tv', 'lg', '4k', 'smart'] },

  // ============ LAPTOPS ============
  { name: 'Apple MacBook Air 13" M2 (8+256GB)', brand: 'Apple', category: 'Electronics', price: 99900, mrp: 112900, stock: 3, description: 'MacBook Air with M2 chip, 13.6" Liquid Retina display, 18-hour battery, fanless design in Midnight.', specifications: { 'Screen Size': '13.6 inch', Chip: 'Apple M2', RAM: '8 GB', Storage: '256 GB SSD', 'Battery Life': 'Up to 18 hours', Weight: '1.24 kg', OS: 'macOS', Ports: '2x Thunderbolt', Color: 'Midnight', Warranty: '1 Year Apple' }, images: [U('photo-1496181133206-80ce9b88a853')], ratings: 4.7, reviewCount: 210, isFeatured: true, emiAvailable: true, emiStarting: 8325, tags: ['laptop', 'apple', 'macbook', 'm2'] },
  { name: 'Apple MacBook Pro 14" M3 Pro (18+512GB)', brand: 'Apple', category: 'Electronics', price: 194900, mrp: 214900, stock: 2, description: 'MacBook Pro 14" with M3 Pro chip, 18GB unified memory, Liquid Retina XDR display, pro-grade power.', specifications: { 'Screen Size': '14.2 inch', Chip: 'Apple M3 Pro', RAM: '18 GB', Storage: '512 GB SSD', 'Battery Life': 'Up to 18 hours', Weight: '1.61 kg', OS: 'macOS', Ports: '3x Thunderbolt 4, HDMI, SDXC', Warranty: '1 Year Apple' }, images: [U('photo-1517336714731-489689fd1ca8')], ratings: 4.8, reviewCount: 95, emiAvailable: true, emiStarting: 16242, tags: ['laptop', 'apple', 'macbook', 'pro'] },
  { name: 'Dell XPS 13 Plus Laptop (16+512GB)', brand: 'Dell', category: 'Electronics', price: 134990, mrp: 149990, stock: 3, description: 'Dell XPS 13 Plus with 13th Gen Intel i7, 13.4" InfinityEdge OLED, precision touchpad, zero-lattice keyboard.', specifications: { 'Screen Size': '13.4 inch', Processor: 'Intel Core i7-1360P', RAM: '16 GB', Storage: '512 GB SSD', Display: 'OLED 3.5K', Weight: '1.26 kg', OS: 'Windows 11 Pro', Battery: '55 Wh', Warranty: '1 Year Dell' }, images: [U('photo-1587202372775-e229f172b9d7')], ratings: 4.6, reviewCount: 45, emiAvailable: true, emiStarting: 11249, tags: ['laptop', 'dell', 'xps', 'windows'] },
  { name: 'HP Pavilion 15 Laptop (16+512GB)', brand: 'HP', category: 'Electronics', price: 64990, mrp: 79990, stock: 6, description: 'HP Pavilion 15 with Intel Core i5, 15.6" FHD display, backlit keyboard and fast SSD storage.', specifications: { 'Screen Size': '15.6 inch', Processor: 'Intel Core i5-1340P', RAM: '16 GB', Storage: '512 GB SSD', Display: 'FHD IPS', Weight: '1.75 kg', OS: 'Windows 11 Home', Battery: '41 Wh', Warranty: '1 Year HP' }, images: [U('photo-1517336714731-489689fd1ca8')], ratings: 4.3, reviewCount: 60, emiAvailable: true, emiStarting: 5416, tags: ['laptop', 'hp', 'pavilion', 'windows'] },

  // ============ TABLETS ============
  { name: 'Apple iPad Pro 11" M4 (8+256GB)', brand: 'Apple', category: 'Electronics', price: 109900, mrp: 119900, stock: 4, description: 'iPad Pro 11" with M4 chip, Ultra Retina XDR display, Apple Pencil Pro support, ultra-thin design.', specifications: { 'Screen Size': '11 inch', Chip: 'Apple M4', RAM: '8 GB', Storage: '256 GB', Display: 'Ultra Retina XDR', Weight: '444 g', Camera: '12 MP', Connectivity: '5G + WiFi', Warranty: '1 Year Apple' }, images: [U('photo-1544244015-0df4b3ffc6b0')], ratings: 4.7, reviewCount: 88, isFeatured: true, emiAvailable: true, emiStarting: 9158, tags: ['tablet', 'ipad', 'apple', 'm4'] },
  { name: 'Samsung Galaxy Tab S9 (8+128GB)', brand: 'Samsung', category: 'Electronics', price: 74990, mrp: 84990, stock: 5, description: 'Samsung Galaxy Tab S9 with Snapdragon 8 Gen 2, 11" Dynamic AMOLED 120Hz, S Pen included.', specifications: { 'Screen Size': '11 inch', Processor: 'Snapdragon 8 Gen 2', RAM: '8 GB', Storage: '128 GB', Display: 'Dynamic AMOLED 120Hz', Battery: '8400 mAh', Weight: '498 g', 'S Pen': 'Included', Warranty: '1 Year Samsung' }, images: [U('photo-1544244015-0df4b3ffc6b0')], ratings: 4.5, reviewCount: 72, emiAvailable: true, emiStarting: 6249, tags: ['tablet', 'samsung', 'tab', 'android'] },

  // ============ HEADPHONES & EARBUDS ============
  { name: 'Sony WH-1000XM5 Wireless Headphones', brand: 'Sony', category: 'Electronics', price: 29990, mrp: 34990, stock: 8, description: 'Sony WH-1000XM5 industry-leading noise cancelling, 30-hour battery, LDAC hi-res audio, crystal clear calls.', specifications: { Type: 'Over-ear Wireless', 'Noise Cancelling': 'Yes', 'Battery Life': '30 hours', Driver: '30mm', Bluetooth: '5.2', Codecs: 'LDAC, AAC, SBC', Charging: 'USB-C Fast Charge', Weight: '250 g', Warranty: '1 Year Sony' }, images: [U('photo-1505740420928-5e560c06d30e')], ratings: 4.8, reviewCount: 320, isFeatured: true, emiAvailable: true, emiStarting: 2499, tags: ['headphones', 'sony', 'anc', 'wireless'] },
  { name: 'Apple AirPods Pro (2nd Gen) with USB-C', brand: 'Apple', category: 'Electronics', price: 24900, mrp: 26900, stock: 10, description: 'AirPods Pro 2 with up to 2x Active Noise Cancellation, Adaptive Audio, USB-C charging case.', specifications: { Type: 'True Wireless', 'Active Noise Cancellation': 'Yes', 'Battery Life': '6 hours + 30 case', Chip: 'H2', Bluetooth: '5.3', 'Water Resistance': 'IPX4', Charging: 'USB-C + MagSafe', Warranty: '1 Year Apple' }, images: [U('photo-1572569511254-d8f925fe2cbb')], ratings: 4.7, reviewCount: 540, isFeatured: true, emiAvailable: true, emiStarting: 2075, tags: ['earbuds', 'apple', 'airpods', 'anc'] },
  { name: 'Samsung Galaxy Buds3 Pro', brand: 'Samsung', category: 'Electronics', price: 19999, mrp: 24999, stock: 12, description: 'Galaxy Buds3 Pro with adaptive ANC, Galaxy AI, blade design, 360 audio and 26-hour battery with case.', specifications: { Type: 'True Wireless', 'Active Noise Cancellation': 'Yes', 'Battery Life': '7 hours + 26 case', Driver: 'Dual driver', Bluetooth: '5.4', 'Water Resistance': 'IP57', Charging: 'USB-C + Wireless', Warranty: '1 Year Samsung' }, images: [U('photo-1572569511254-d8f925fe2cbb')], ratings: 4.4, reviewCount: 140, emiAvailable: true, emiStarting: 1667, tags: ['earbuds', 'samsung', 'anc', 'wireless'] },
  { name: 'boAt Rockerz 450 Bluetooth Headphones', brand: 'boAt', category: 'Electronics', price: 1499, mrp: 3990, stock: 15, description: 'boAt Rockerz 450 over-ear headphones with 40mm drivers, up to 15 hours playtime, plush earcups.', specifications: { Type: 'Over-ear Wireless', 'Battery Life': '15 hours', Driver: '40mm', Bluetooth: '5.0', Charging: 'Micro-USB', Weight: '155 g', Mic: 'Yes', Warranty: '1 Year boAt' }, images: [U('photo-1505740420928-5e560c06d30e')], ratings: 4.1, reviewCount: 1500, isOnOffer: true, offerLabel: 'Best Seller', emiAvailable: true, emiStarting: 125, tags: ['headphones', 'boat', 'budget', 'wireless'] },

  // ============ SMART WATCHES ============
  { name: 'Apple Watch Series 10 GPS (46mm)', brand: 'Apple', category: 'Electronics', price: 46900, mrp: 48900, stock: 6, description: 'Apple Watch Series 10 with bigger Always-On Retina display, sleep apnoea alerts, 18-hour battery.', specifications: { 'Case Size': '46mm', Display: 'Always-On Retina LTPO3', Sensors: 'Heart rate, ECG, Temp, Oxygen', 'Battery Life': '18 hours', 'Water Resistance': '50m', Connectivity: 'GPS + Bluetooth + WiFi', Chip: 'S10 SiP', Color: 'Jet Black', Warranty: '1 Year Apple' }, images: [U('photo-1523275335684-37898b6baf30')], ratings: 4.6, reviewCount: 180, isFeatured: true, emiAvailable: true, emiStarting: 3908, tags: ['smartwatch', 'apple', 'watch'] },
  { name: 'Samsung Galaxy Watch 7 (44mm) BT', brand: 'Samsung', category: 'Electronics', price: 32999, mrp: 37999, stock: 7, description: 'Galaxy Watch 7 with BioActive sensor, sleep coaching, energy score and dual-band GPS.', specifications: { 'Case Size': '44mm', Display: 'Super AMOLED 1.5"', Sensors: 'Heart rate, ECG, Body composition, Temp', 'Battery Life': '40 hours', 'Water Resistance': '5ATM + IP68', Connectivity: 'Bluetooth + WiFi', OS: 'Wear OS 5', Warranty: '1 Year Samsung' }, images: [U('photo-1523275335684-37898b6baf30')], ratings: 4.5, reviewCount: 110, emiAvailable: true, emiStarting: 2750, tags: ['smartwatch', 'samsung', 'wearos'] },
  { name: 'Noise ColorFit Pro 4 Smart Watch', brand: 'Noise', category: 'Electronics', price: 2299, mrp: 5499, stock: 20, description: 'Noise ColorFit Pro 4 with 1.85" AMOLED display, Bluetooth calling, 150+ sports modes and 7-day battery.', specifications: { Display: '1.85" AMOLED', 'Bluetooth Calling': 'Yes', 'Sports Modes': '150+', 'Battery Life': '7 days', 'Water Resistance': 'IP68', Sensors: 'Heart rate, SpO2', Straps: 'Silicone', Warranty: '1 Year Noise' }, images: [U('photo-1523275335684-37898b6baf30')], ratings: 4.0, reviewCount: 900, isOnOffer: true, offerLabel: 'Deal of the Day', emiAvailable: true, emiStarting: 192, tags: ['smartwatch', 'noise', 'budget'] },

  // ============ SPEAKERS ============
  { name: 'JBL Flip 6 Bluetooth Speaker', brand: 'JBL', category: 'Electronics', price: 10999, mrp: 14999, stock: 9, description: 'JBL Flip 6 portable speaker with rich JBL Original Pro Sound, 12-hour playtime, IP67 waterproof.', specifications: { Type: 'Portable Bluetooth', Power: '30W RMS', 'Battery Life': '12 hours', 'Water Resistance': 'IP67', Bluetooth: '5.1', Weight: '550 g', Color: 'Black', Warranty: '1 Year JBL' }, images: [U('photo-1608043152269-423dbba4e7e1')], ratings: 4.5, reviewCount: 260, emiAvailable: true, emiStarting: 917, tags: ['speaker', 'jbl', 'bluetooth', 'portable'] },
  { name: 'Amazon Echo Dot (5th Gen) Smart Speaker', brand: 'Amazon', category: 'Electronics', price: 4499, mrp: 6499, stock: 14, description: 'Echo Dot 5th Gen with improved audio, Alexa smart home hub, temperature sensor and motion detection.', specifications: { Type: 'Smart Speaker', Assistant: 'Alexa', 'Smart Home Hub': 'Yes', Audio: '1.73" front-firing', 'Temperature Sensor': 'Yes', Connectivity: 'WiFi + Bluetooth', Color: 'Charcoal', Warranty: '1 Year Amazon' }, images: [U('photo-1608043152269-423dbba4e7e1')], ratings: 4.3, reviewCount: 700, emiAvailable: true, emiStarting: 375, tags: ['speaker', 'alexa', 'smart home'] },
  { name: 'Marshall Emberton II Portable Speaker', brand: 'Marshall', category: 'Electronics', price: 16999, mrp: 19999, stock: 5, description: 'Marshall Emberton II with 30+ hours of playtime, rugged design, IP67 rating and multi-directional sound.', specifications: { Type: 'Portable Bluetooth', Power: '10W', 'Battery Life': '30+ hours', 'Water Resistance': 'IP67', Bluetooth: '5.1', Weight: '700 g', Color: 'Black & Brass', Warranty: '1 Year Marshall' }, images: [U('photo-1550009158-9ebf69173e03')], ratings: 4.6, reviewCount: 90, emiAvailable: true, emiStarting: 1417, tags: ['speaker', 'marshall', 'portable'] },

  // ============ CAMERAS ============
  { name: 'Canon EOS R50 Mirrorless Camera (18-45mm)', brand: 'Canon', category: 'Electronics', price: 61990, mrp: 69990, stock: 3, description: 'Canon EOS R50 mirrorless camera with 24.2MP APS-C sensor, 4K video, DIGIC X processor, RF-S 18-45mm lens.', specifications: { Sensor: '24.2MP APS-C CMOS', Lens: 'RF-S 18-45mm f/4.5-6.3 IS STM', Video: '4K 30p', 'Processor': 'DIGIC X', 'Autofocus': 'Dual Pixel CMOS AF II', 'Viewfinder': 'Electronic OLED', Screen: '3" Vari-angle', Weight: '375 g', Warranty: '1 Year Canon' }, images: [U('photo-1516035069371-29a1b244cc32')], ratings: 4.5, reviewCount: 40, emiAvailable: true, emiStarting: 5166, tags: ['camera', 'canon', 'mirrorless'] },
  { name: 'Sony Alpha ZV-E10 Mirrorless Camera', brand: 'Sony', category: 'Electronics', price: 74990, mrp: 84990, stock: 2, description: 'Sony ZV-E10 vlogging camera with 24.2MP APS-C sensor, 4K video, flip screen and advanced vlog features.', specifications: { Sensor: '24.2MP APS-C CMOS', Video: '4K 30p', 'Processor': 'BIONZ X', 'Autofocus': 'Real-time Eye AF', Screen: '3" flip-out touch', Mic: '3-capsule directional', Weight: '343 g', Warranty: '1 Year Sony' }, images: [U('photo-1560769629-975ec94e6a86')], ratings: 4.4, reviewCount: 35, emiAvailable: true, emiStarting: 6249, tags: ['camera', 'sony', 'vlog'] },

  // ============ GAMING ============
  { name: 'Sony PlayStation 5 Slim Console (1TB)', brand: 'Sony', category: 'Electronics', price: 54990, mrp: 59990, stock: 3, description: 'PlayStation 5 Slim with 1TB SSD, ultra-fast loading, 4K 120fps gaming, haptic feedback DualSense.', specifications: { Storage: '1TB SSD', 'Resolution': 'Up to 4K 120fps', CPU: '8-core AMD Zen 2', GPU: '10.28 TFLOPs', Controller: 'DualSense', Optical: '4K UHD Blu-ray', Weight: '3.2 kg', Warranty: '1 Year Sony' }, images: [U('photo-1486401899868-0e435ed85128')], ratings: 4.7, reviewCount: 210, isFeatured: true, emiAvailable: true, emiStarting: 4583, tags: ['gaming', 'ps5', 'sony', 'console'] },
  { name: 'Xbox Series X Console (1TB)', brand: 'Microsoft', category: 'Electronics', price: 49990, mrp: 54990, stock: 2, description: 'Xbox Series X with 12 TFLOPs of power, 4K 120fps, 1TB SSD, Quick Resume and Game Pass ready.', specifications: { Storage: '1TB SSD', 'Resolution': '4K 120fps', CPU: '8-core AMD Zen 2', GPU: '12 TFLOPs', Controller: 'Xbox Wireless', Optical: '4K UHD Blu-ray', Weight: '4.4 kg', Warranty: '1 Year Microsoft' }, images: [U('photo-1547394765-185e1e68f34e')], ratings: 4.6, reviewCount: 95, emiAvailable: true, emiStarting: 4166, tags: ['gaming', 'xbox', 'console'] },
  { name: 'Sony DualSense Wireless Controller', brand: 'Sony', category: 'Electronics', price: 5990, mrp: 7490, stock: 15, description: 'DualSense wireless controller with haptic feedback, adaptive triggers, built-in mic and USB-C.', specifications: { Connectivity: 'Bluetooth + USB-C', Features: 'Haptic feedback, Adaptive triggers', 'Built-in Mic': 'Yes', Battery: '1560 mAh', Color: 'White', Warranty: '1 Year Sony' }, images: [U('photo-1558618666-fcd25c85cd64')], ratings: 4.5, reviewCount: 300, emiAvailable: true, emiStarting: 499, tags: ['gaming', 'controller', 'ps5'] },

  // ============ PC ACCESSORIES ============
  { name: 'Dell 27" 4K UHD Monitor (P2723QE)', brand: 'Dell', category: 'Electronics', price: 39990, mrp: 47990, stock: 6, description: 'Dell 27" 4K UHD monitor with IPS panel, 99% sRGB, USB-C with 90W charging, comfortable viewing.', specifications: { 'Screen Size': '27 inch', Resolution: '4K UHD 3840x2160', Panel: 'IPS', 'Refresh Rate': '60 Hz', Ports: 'USB-C 90W, HDMI, DP', 'Response Time': '5ms', Warranty: '3 Year Dell' }, images: [U('photo-1527443224154-c4a3942d3acf')], ratings: 4.5, reviewCount: 55, emiAvailable: true, emiStarting: 3333, tags: ['monitor', 'dell', '4k', 'pc'] },
  { name: 'Logitech G915 X Mechanical Keyboard', brand: 'Logitech', category: 'Electronics', price: 24999, mrp: 29999, stock: 8, description: 'Logitech G915 X LIGHTSPEED wireless mechanical keyboard with GL tactile switches, RGB, compact TKL.', specifications: { Switch: 'GL Tactile', Connectivity: 'LIGHTSPEED + BT + USB-C', RGB: 'Per-key RGB', Battery: 'Up to 800 hours', Layout: 'Tenkeyless', Weight: '880 g', Warranty: '2 Year Logitech' }, images: [U('photo-1547082299-de196ea013d6')], ratings: 4.6, reviewCount: 70, emiAvailable: true, emiStarting: 2083, tags: ['keyboard', 'logitech', 'gaming', 'pc'] },
  { name: 'Logitech MX Master 3S Mouse', brand: 'Logitech', category: 'Electronics', price: 8499, mrp: 10999, stock: 12, description: 'Logitech MX Master 3S with 8K DPI, silent clicks, MagSpeed scroll wheel and multi-device pairing.', specifications: { DPI: '8000', Connectivity: 'BT + USB-C receiver', Buttons: '7 programmable', Battery: 'Up to 70 days', Sensor: 'Darkfield 8K', Weight: '141 g', Warranty: '1 Year Logitech' }, images: [U('photo-1527814050087-3793815479db')], ratings: 4.6, reviewCount: 400, emiAvailable: true, emiStarting: 708, tags: ['mouse', 'logitech', 'pc'] },

  // ============ NETWORKING ============
  { name: 'TP-Link Archer AX55 Wi-Fi 6 Router', brand: 'TP-Link', category: 'Electronics', price: 5499, mrp: 7999, stock: 18, description: 'TP-Link Archer AX55 AX3000 dual-band Wi-Fi 6 router with speeds up to 3Gbps and easy app setup.', specifications: { Standard: 'Wi-Fi 6 (802.11ax)', Speed: 'AX3000 (2402+574 Mbps)', Bands: 'Dual-band', Ports: '4x Gigabit LAN + 1x WAN', Security: 'WPA3', Antenna: '4 external', Warranty: '2 Year TP-Link' }, images: [U('photo-1605100804763-247f67b3557e')], ratings: 4.3, reviewCount: 320, emiAvailable: true, emiStarting: 458, tags: ['router', 'wifi6', 'networking'] },
  { name: 'TP-Link Tapo C210 Smart Camera', brand: 'TP-Link', category: 'Electronics', price: 2499, mrp: 3999, stock: 20, description: 'Tapo C210 2K QHD pan-tilt home security camera with night vision, motion detection and two-way audio.', specifications: { Resolution: '2K QHD', 'Pan/Tilt': '360/114 degrees', 'Night Vision': '850nm IR', Storage: 'MicroSD + Cloud', Audio: 'Two-way', Warranty: '1 Year TP-Link' }, images: [U('photo-1585790050230-5dd28404ccb9')], ratings: 4.2, reviewCount: 600, emiAvailable: true, emiStarting: 208, tags: ['camera', 'security', 'smart home'] },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI || process.env.MONGO_URI || 'mongodb://localhost:27017/hello_mobiles');
  console.log('Connected to MongoDB');

  await Product.deleteMany({ category: 'Electronics' });
  console.log('Cleared existing Electronics products');

  let count = 0;
  for (const p of products) {
    await Product.create(p);
    count++;
    console.log(`[${count}/${products.length}] ${p.name} (${p.price})`);
  }

  console.log(`\nDone! Seeded ${count} Electronics products.`);
  process.exit(0);
}

seed().catch(e => { console.error('Failed:', e); process.exit(1); });
